# Generated by Django 3.0.5 on 2020-10-17 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0003_auto_20201016_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
