# Generated by Django 3.0.2 on 2020-10-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fine', '0003_auto_20201016_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='date_paid',
            field=models.DateField(blank=True, null=True),
        ),
    ]
